-- ============================================================================
-- 202607070011_seed_default_roles.sql
-- Seeds the default role catalogue. Contains no personal data.
-- Role->permission wiring mirrors @ubm-klar/access-control ROLE_PERMISSIONS.
-- ============================================================================

insert into roles (role_key, display_name_sv, description_sv, is_no_pii_role, is_break_glass) values
  ('municipality_admin','Kommunadministratör','Administrerar användare, roller, integrationer och regler.',false,false),
  ('system_owner','Systemägare','Ansvarar för systemet och dess förvaltning.',false,false),
  ('social_services_manager','Chef socialtjänst','Läsbehörighet över verksamhetens ärenden och kontroller.',false,false),
  ('lss_case_worker','LSS-handläggare','Handlägger LSS-ärenden enligt behovsprincipen.',false,false),
  ('economic_assistance_case_worker','Handläggare ekonomiskt bistånd','Handlägger ärenden om ekonomiskt bistånd.',false,false),
  ('controller','Controller','Genomför betalningskontroll och avstämning.',false,false),
  ('finance_officer','Ekonom','Hanterar betalningsfiler och mottagarregister.',false,false),
  ('lawyer','Jurist','Genomför juridisk granskning och sekretessprövning.',false,false),
  ('dpo','Dataskyddsombud','Granskar behandling, åtkomst och utlämnanden.',false,false),
  ('information_security_officer','Informationssäkerhetsansvarig','Ansvarar för säkerhetskontroller och uppföljning.',false,false),
  ('internal_auditor','Internrevisor','Granskar logg- och revisionsdata.',false,false),
  ('ubm_export_manager','UBM-exportansvarig','Hanterar UBM-förfrågningar, exportförslag och godkännanden.',false,false),
  ('control_investigator','Kontrollutredare','Utreder kontrollärenden och felaktiga utbetalningar.',false,false),
  ('read_only_reviewer','Läsbehörig granskare','Endast läsbehörighet för granskning.',false,false),
  ('support_technician_no_pii','Supporttekniker (utan personuppgifter)','Teknisk support utan åtkomst till personuppgifter.',true,false),
  ('technical_admin_no_pii','Teknisk administratör (utan personuppgifter)','Teknisk drift utan åtkomst till personuppgifter.',true,false),
  ('break_glass_admin','Break glass-administratör','Nödåtkomst med tidsgräns, skäl och efterhandsgranskning.',false,true),
  ('platform_admin_no_pii','Plattformsadministratör (utan personuppgifter)','Leverantörens plattformsadministration utan personuppgifter.',true,false),
  ('billing_admin_no_pii','Faktureringsadministratör (utan personuppgifter)','Fakturering och licenser utan personuppgifter.',true,false),
  ('implementation_consultant_no_pii','Införandekonsult (utan personuppgifter)','Stödjer införande utan åtkomst till personuppgifter.',true,false);

insert into permissions (permission_key, description) values
  ('person.read','Read person records'),
  ('person.search','Search persons'),
  ('person.sensitive_field.reveal','Reveal masked sensitive fields with reason'),
  ('case.lss.read','Read LSS cases'),
  ('case.lss.write','Handle LSS cases'),
  ('case.ea.read','Read economic assistance cases'),
  ('case.ea.write','Handle economic assistance cases'),
  ('case.control.read','Read control cases'),
  ('case.control.write','Handle control cases'),
  ('case.control.decide','Decide control cases'),
  ('payment.read','Read payments'),
  ('payment.reconcile','Run payment reconciliation'),
  ('payment.recipient.change','Change payment recipients (maker-checker)'),
  ('import.run','Run imports'),
  ('import.configure','Configure imports and integrations'),
  ('document.read','Read documents'),
  ('document.download','Download documents'),
  ('document.redact','Redact documents'),
  ('document.export.approve','Approve document export'),
  ('ubm.request.register','Register UBM requests'),
  ('ubm.request.read','Read UBM requests'),
  ('ubm.proposal.create','Create UBM export proposals'),
  ('ubm.proposal.review','Review UBM export proposals'),
  ('ubm.export.approve','Approve UBM exports (maker-checker)'),
  ('ubm.export.send','Send/download approved UBM exports'),
  ('ubm.notification.handle','Handle UBM notifications'),
  ('audit.read','Read audit logs'),
  ('access_log.read','Read data access logs'),
  ('legal.review','Perform legal review'),
  ('dpo.review','Perform DPO review'),
  ('archive.manage','Manage archive and retention'),
  ('archive.export','Run e-archive exports'),
  ('public_record.handle','Handle public record requests'),
  ('secrecy.review','Perform secrecy review'),
  ('retention.execute','Execute retention/disposal decisions'),
  ('exit_export.run','Run exit exports'),
  ('users.manage','Manage users'),
  ('roles.manage','Manage roles'),
  ('rules.configure','Configure risk rules'),
  ('integrations.configure','Configure integrations'),
  ('readiness.manage','Manage readiness gates'),
  ('support.technical_status.read','Read technical status without PII'),
  ('billing.read','Read billing status'),
  ('platform.tenants.manage','Manage platform tenants'),
  ('break_glass.initiate','Initiate break-glass session');
